### ISSUE TITLE
public static methods activate() and deactivate() missing

### ISSUE THREAD

**Issue by dvdmierden** [laposta/connect-woocommerce#1]
`Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, class Laposta_Woocommerce_Template does not have a method "activate" in /path/to/httpdocs/wp-includes/class-wp-hook.php:303 Stack trace: #0 /path/to/httpdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #1 /path/to/httpdocs/wp-includes/plugin.php(470): WP_Hook->do_action() #2 /path/to/httpdocs/wp-admin/plugins.php(193): do_action() #3 {main} thrown in /path/to/httpdocs/wp-includes/class-wp-hook.php on line 303`

I've added
```
public static function activate() {
			
}
public static function deactivate() {
			
}
```
To the class, bu I'm not sure if there's any specific code that should be run.

**Comment by roelleor** [comment]
Thanks for letting us know and my apologies for the delay. This is fixed in version 1.5.1 by removing the register_activation_hook and register_deactivation_hook calling these methods.
